#Requires -Version 3.0
<#
.SYNOPSIS
    Builds PunyStaub, generates both Inform7 and PunyStaub transcripts from the
    same walkthrough, and produces a diff file for analysis.

.DESCRIPTION
    Steps:
    1. Build staub.z5 and generate the PunyStaub transcript (calls build.ps1).
     2. Use the Inform7 transcript generated by the Staub Build task:
         ..\Inform7\Tests\Staub.transcript.inform7.txt.
    3. Call diff_transcripts.py to compare both transcripts and write
       build\Staub.transcript.diff.txt.

    Pass -RebuildOnly to skip the diff step (build + transcripts only).
    Pass -DiffOnly  to skip the build step (diff from existing transcripts).
#>
param(
    [switch]$RebuildOnly,
    [switch]$DiffOnly,
    [switch]$RegenI7    # force re-run of Inform7 transcript even if cached
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$SCRIPT_DIR   = $PSScriptRoot
$PUNYINFORMDE = "$SCRIPT_DIR\..\..\..\PunyInformDE"
$PYTHON       = if (Test-Path "$SCRIPT_DIR\..\..\.venv\Scripts\python.exe") {
                    "$SCRIPT_DIR\..\..\.venv\Scripts\python.exe"
                } elseif (Test-Path "$PUNYINFORMDE\.venv\Scripts\python.exe") {
                    "$PUNYINFORMDE\.venv\Scripts\python.exe"
                } else {
                    "python"
                }

# ─── Step 1: Build ───────────────────────────────────────────────────────────
if (-not $DiffOnly) {
    Write-Host "`n=== Building PunyStaub + generating transcript ===" -ForegroundColor Cyan
    & powershell -ExecutionPolicy Bypass -File "$SCRIPT_DIR\build.ps1"
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Build failed."
        exit $LASTEXITCODE
    }
}

if ($RebuildOnly) {
    Write-Host "`nDone (rebuild only)." -ForegroundColor Green
    exit 0
}

# ─── Step 2 + 3: Generate Inform7 samewalk transcript and diff ───────────────
Write-Host "`n=== Comparing transcripts ===" -ForegroundColor Cyan

$diffArgs = @("$SCRIPT_DIR\diff_transcripts.py")
if ($RegenI7) { $diffArgs += "--regen-i7" }

& $PYTHON @diffArgs
if ($LASTEXITCODE -ne 0) {
    Write-Error "diff_transcripts.py failed."
    exit $LASTEXITCODE
}

Write-Host "`nDone. Diff file: $SCRIPT_DIR\build\Staub.transcript.diff.txt" -ForegroundColor Green
