'Preview: Alt-D
'https://plantuml.com/de/creole
'listopeniconic

@startuml Staub
"<&briefcase>  **Bag**" --> "<&briefcase>  **Money**"
"<&briefcase>  **Bag**" --> "<&briefcase>  **Revolver**"
"<&briefcase>  **Bag**" --> "<&person>  Lucy-Happened"
"<&person>  Lucy-Happened" --> "<&person>  Sheriff-Leave"
"<&person>  Sheriff-Leave" --> "<&briefcase>  **Handkerchief**"
"<&briefcase>  **Handkerchief**" --> "<&person>  Ella-Handkerchief"
"<&briefcase>  **Handkerchief**" --> "<&person>  Sheriff-Handkerchief"
"<&briefcase>  **Handkerchief**" --> "<&person>  Barber-Mine"
"<&person>  Barber-Mine" --> "Molly lendable"
"<&person>  Barber-Mine" --> "<&person>  Barber-Shovel"
"<&briefcase>  **Money**" --> "<&person>  Ella-Coffee"
"<&person>  Ella-Coffee" --> "<&briefcase>  **Cookie**"
"<&briefcase>  **Cookie**" --> "Molly trusting"
"Molly trusting" --> "<&briefcase>  **Molly**"
"Molly lendable" --> "<&briefcase>  **Molly**"
"<&briefcase>  **Molly**" --> "Crevice discovered"
"Crevice discovered" --> "<&person>  Bill-Crowbar"
"Crevice widened" --> "<&person>  Bill-Crevice"
"<&person>  Bill-Crowbar" --> "<&person>  Bill-Wife"
"<&person>  Bill-Wife" --> "Bills-Wife named"
"Bills-Wife named" --> "<&briefcase>  **Pince-nez**"
"Bills-Wife Grave found"--> "<&briefcase>  **Pince-nez**"
"<&briefcase>  **Pince-nez**" --> "<&briefcase>  **Crowbar**"
"<&briefcase>  **Crowbar**" --> "Crevice widened"
"Mast examined" --> "<&briefcase>  **Rod**"
"<&briefcase>  **Rod**" --> "Cave entered"
"Crevice widened" --> "Cave entered"
"Cave entered" --> "<&person>  Ella-Lamp"
"<&person>  Ella-Lamp" --> "<&briefcase>  **Lamp**"
"<&briefcase>  **Lamp**" --> "<&briefcase>  **Matches**"
"<&briefcase>  **Money**" --> "<&briefcase>  **Matches**"
"<&briefcase>  **Matches**" --> "Precipice discovered"
"Sand examined" --> "<&briefcase>  **Shovel**"
"<&person>  Barber-Shovel" --> "<&briefcase>  **Shovel**"
"<&briefcase>  **Shovel**" --> "Plate found"
"Plate found" --> "Plate opened"
"<&briefcase>  **Crowbar**" --> "Plate opened"
"Plate opened" --> "<&briefcase>  **Rope**"
"<&briefcase>  **Rope**" --> "Precipice rappelled"
"Precipice discovered" --> "Precipice rappelled"
"Precipice rappelled" --> "Guard knocked out"
"<&briefcase>  **Handkerchief**" --> "Guard knocked out"
"<&briefcase>  **Crowbar**" --> "Guard knocked out"
"<&briefcase>  **Revolver**" --> "Wedge removed"
"Guard knocked out" --> Wedge removed
"Wedge removed" --> "**End**"
@enduml