'Preview: Alt-D
'https://plantuml.com/de/creole
'listopeniconic

@startuml Staub
"<&briefcase>  **Tasche**" --> "<&briefcase>  **Geld**"
"<&briefcase>  **Tasche**" --> "<&briefcase>  **Revolver**"
"<&briefcase>  **Tasche**" --> "<&person>  Lucy-Passiert"
"<&person>  Lucy-Passiert" --> "<&person>  Sheriff-Gehen"
"<&person>  Sheriff-Gehen" --> "<&briefcase>  **Taschentuch**"
"<&briefcase>  **Taschentuch**" --> "<&person>  Ella-Taschentuch"
"<&briefcase>  **Taschentuch**" --> "<&person>  Sheriff-Taschentuch"
"<&briefcase>  **Taschentuch**" --> "<&person>  Barbier-Mine"
"<&person>  Barbier-Mine" --> "Molly ausleihbar"
"<&person>  Barbier-Mine" --> "<&person>  Barbier-Schaufel"
"<&briefcase>  **Geld**" --> "<&person>  Ella-Kaffee"
"<&person>  Ella-Kaffee" --> "<&briefcase>  **Keks**"
"<&briefcase>  **Keks**" --> "Molly zutraulich"
"Molly zutraulich" --> "<&briefcase>  **Molly**"
"Molly ausleihbar" --> "<&briefcase>  **Molly**"
"<&briefcase>  **Molly**" --> "Spalt entdeckt"
"Spalt entdeckt" --> "<&person>  Bill-Kuhfuß"
"Spalt geweitet" --> "<&person>  Bill-Spalt"
"<&person>  Bill-Kuhfuß" --> "<&person>  Bill-Frau"
"<&person>  Bill-Frau" --> "Bills-Frau Vorname bekannt"
"Bills-Frau Vorname bekannt" --> "<&briefcase>  **Zwicker**"
"Bills-Frau Grab gefunden"--> "<&briefcase>  **Zwicker**"
"<&briefcase>  **Zwicker**" --> "<&briefcase>  **Brecheisen**"
"<&briefcase>  **Brecheisen**" --> "Spalt geweitet"
"Mast untersucht" --> "<&briefcase>  **Stange**"
"<&briefcase>  **Stange**" --> "Höhle betreten"
"Spalt geweitet" --> "Höhle betreten"
"Höhle betreten" --> "<&person>  Ella-Laterne"
"<&person>  Ella-Laterne" --> "<&briefcase>  **Laterne**"
"<&briefcase>  **Laterne**" --> "<&briefcase>  **Zündhölzer**"
"<&briefcase>  **Geld**" --> "<&briefcase>  **Zündhölzer**"
"<&briefcase>  **Zündhölzer**" --> "Abgrund entdeckt"
"Sand untersucht" --> "<&briefcase>  **Schaufel**"
"<&person>  Barbier-Schaufel" --> "<&briefcase>  **Schaufel**"
"<&briefcase>  **Schaufel**" --> "Podest gefunden"
"Podest gefunden" --> "Luke geöffnet"
"<&briefcase>  **Brecheisen**" --> "Luke geöffnet"
"Luke geöffnet" --> "<&briefcase>  **Seil**"
"<&briefcase>  **Seil**" --> "Abgrund abgeseilt"
"Abgrund entdeckt" --> "Abgrund abgeseilt"
"Abgrund abgeseilt" --> "Wache ausgeschaltet"
"<&briefcase>  **Taschentuch**" --> "Wache ausgeschaltet"
"<&briefcase>  **Brecheisen**" --> "Wache ausgeschaltet"
"<&briefcase>  **Revolver**" --> "Keil entfernt"
"Wache ausgeschaltet" --> Keil entfernt
"Keil entfernt" --> "**Ende**"
@enduml